const AVAILABLE_LANGUAGES_ENV = process.env.REACT_APP_AVAILABLE_LANGUAGES
  ? process.env.REACT_APP_AVAILABLE_LANGUAGES.split(',')
  : ['en', 'es'];

export const DEFAULT_LANGUAGE = AVAILABLE_LANGUAGES_ENV[0];

export const LIST_LANGUAGES = AVAILABLE_LANGUAGES_ENV;
